version: '2'
services:
    nginx:
      image: nginx
      ports:
        - "8000:80"
      links:
        - app
      volumes:
        - "./www:/var/www"
        - "./.docker/config/nginx/vhost/sf4_vhost:/etc/nginx/conf.d/030-sf4.conf:ro"
    app:
      build: .docker
      links:
        - mysql
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./www:/var/www"
      ports:
        - "9000:9000"
      environment:
        - APP_ENV=dev
        - APP_SECRET=d6f9c4f8997e182557e0602aa11c68ca
        - DATABASE_DRIVER=mysql
        - DATABASE_HOST=mysql
        - DATABASE_USER=symfony_test
        - DATABASE_PASSWORD=symfony_test
        - DATABASE_NAME=symfony_test
        - DATABASE_PORT=3306
      working_dir: "/var/www"
    mysql:
      image: mysql:5.7  
      command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
      environment:
        - "MYSQL_ROOT_PASSWORD=symfony_test"
        - "MYSQL_USER=symfony_test"
        - "MYSQL_PASSWORD=symfony_test"
        - "MYSQL_DATABASE=symfony_test"
      ports:
        - "33060:3306"
